### PR TITLE
`TokenMutator` returns `Mutant`s and more precise mutation location

### PR DESCRIPTION
**Pull request by Nhaajt**
This PR changes the return type of token mutators from `String` to `Mutant`. By doing so, a token mutator now has more control over the information (e.g. location of the mutation, description, etc.) of each `Mutant` mutated by it.

This change means:
- **From the outside, `Weapon-regeX` should have NO behavioral difference.**
- Mutate/Apply a `RegexTree` to a `TokenMutator` now returns a sequence of `Mutant`. This is also the case, for `TokenMutatorJS` and `MutantJS`.
- All existing token mutators that are descendants of `TokenMutator` have been adapted to this change.
- Any user-define token mutator that is a descendant of `TokenMutator` needs to adapt to this change. ([👇 Guide](#Adapt-token-mutator-to-return-`Mutant`))
- `TreeMutator` now only traverses the tree, repacks `Mutant`s with (more) complete patterns, and not create entirely new `Mutant`s. New `Mutant`s are only created by the token mutators.

This PR also updates the existing token mutators to produce `Mutant`s with more precise mutation locations, enabled by the above change. ([👇 Mutation location changes](#Mutation-location-changes))

### `BOLRemoval`
```scala
// Before
"^HelloWorld" -> "HelloWorld"
 └──────────┘
// After
"^HelloWorld" -> "HelloWorld"
 └┘
```

### `EOLRemoval`
```scala
// Before
"HelloWorld$" -> "HelloWorld"
 └──────────┘
// After
"HelloWorld$" -> "HelloWorld"
           └┘
```

### `GroupToNCGroup`
```scala
// Before
"(HelloWorld)" -> "(?:HelloWorld)"
 └───────────┘
// After
"(HelloWorld)" -> "(?:HelloWorld)"
 └┘
```

### `LookaroundNegation`
```scala
// Before
"(?=HelloWorld)"  <-> "(?!HelloWorld)"
 └─────────────┘       └─────────────┘
"(?<=HelloWorld)" <-> "(?<!HelloWorld)"
 └──────────────┘      └──────────────┘
// After
"(?=HelloWorld)"  <-> "(?!HelloWorld)"
 └──┘                  └──┘
"(?<=HelloWorld)" <-> "(?<!HelloWorld)"
 └───┘                 └───┘
```

### `CharClassNegation`
```scala
// Before
"[HelloWorld]" <-> "[^HelloWorld]"
 └───────────┘      └────────────┘
// After
"[HelloWorld]" <-> "[^HelloWorld]"
 └┘                 └─┘
```

### `CharClassChildRemoval`
```scala
// Before
"[HelloWorld]" -> "[HellWorld]"
 └───────────┘     └──────────┘
// After
"[HelloWorld]" -> "[HellWorld]"
      └┘
```

### `POSIXCharClassNegation`
```scala
// Before
"""\p{Alpha}""" <-> """\P{Alpha}"""
   └────────┘          └────────┘
// After
"""\p{Alpha}""" <-> """\P{Alpha}"""
   └──┘                └──┘
```

### `QuantifierRemoval`
```scala
// Before
"(HelloWorld)*" -> "(HelloWorld)"
 └────────────┘
// After
"(HelloWorld)*" -> "(HelloWorld)"
             └┘
```

### `QuantifierNChange`
```scala
// Before
"(HelloWorld){10}" -> "(HelloWorld){10,}", "(HelloWorld){0,10}"
 └───────────────┘
// After
"(HelloWorld){10}" -> "(HelloWorld){10,}", "(HelloWorld){0,10}"
             └───┘
```

### `QuantifierNOrMoreModification`
```scala
// Before
"(HelloWorld){10,}" -> "(HelloWorld){9,}", "(HelloWorld){11,}"
 └────────────────┘
// After
"(HelloWorld){10,}" -> "(HelloWorld){9,}", "(HelloWorld){11,}"
             └────┘
```

### `QuantifierNOrMoreChange`
```scala
// Before
"(HelloWorld){10,}" -> "(HelloWorld){10}"
 └────────────────┘
// After
"(HelloWorld){10,}" -> "(HelloWorld){10}"
             └────┘
```

### `QuantifierNMModification`
```scala
// Before
"(HelloWorld){10,20}" -> "(HelloWorld){9,20}", "(HelloWorld){11,20}",
 └──────────────────┘    "(HelloWorld){10,19}", "(HelloWorld){10,21}"
// After
"(HelloWorld){10,20}" -> "(HelloWorld){9,20}", "(HelloWorld){11,20}",
             └──────┘    "(HelloWorld){10,19}", "(HelloWorld){10,21}"
```

### `QuantifierShortModification`
```scala
// Before
"(HelloWorld)*" -> "(HelloWorld){0,0}", "(HelloWorld){0,2}",
 └────────────┘    "(HelloWorld){1,1}"
// After
"(HelloWorld)*" -> "(HelloWorld){9,20}", "(HelloWorld){11,20}",
             └┘    "(HelloWorld){10,19}", "(HelloWorld){10,21}"
```

### `QuantifierShortChange`
```scala
// Before
"(HelloWorld)*" -> "(HelloWorld){0}"
 └────────────┘
// After
"(HelloWorld)*" -> "(HelloWorld){0}"
             └┘
```

### `QuantifierReluctantAddition`
```scala
// Before
"(HelloWorld)+" -> "(HelloWorld)+?"
 └────────────┘
// After
"(HelloWorld)+" -> "(HelloWorld)+?"
             └┘
```

## Adapt token mutator to return `Mutant`
Due to the return type of token mutators change from `String` to `Mutant`, any token mutator that is a descendant of `TokenMutator` needs to adapt to this. 

This PR also provides some helper functions to make this adaptation easier. These are extension methods that convert a `String` into a `Mutant` **within the scope of each `TokenMutator`** by filling in the `Mutant` data with the information from the containing `TokenMutator`.
- Convert a mutated pattern string into a `Mutant` at the provided location.
```scala
"Pattern".toMutantAt(loc: Location)
```
- Convert a mutated pattern string into a `Mutant` with the location taken from the provided token.
```scala
"Pattern".toMutantOf(token: RegexTree)
```
- Convert a mutated pattern string into a `Mutant` with the location starts from the start of the provided token and ends at the start of the token's first child. <sup>(*)</sup>
  - *Sample results:* [`GroupToNCGroup`](#`GroupToNCGroup`), [`LookaroundNegation`](#`LookaroundNegation`), [`CharClassNegation`](#`CharClassNegation`), [`POSIXCharClassNegation`](#`POSIXCharClassNegation`)
```scala
"Pattern".toMutantBeforeChildrenOf(token: RegexTree)
```
- Convert a mutated pattern string into a `Mutant` with the location starts from the end of the provided token's last child and ends at the end of the token. <sup>(*)</sup>
  - *Sample results:* [`QuantifierNChange`](#`QuantifierNChange`), [`QuantifierNOrMoreModification`](#`QuantifierNOrMoreModification`), [`QuantifierNOrMoreChange`](#`QuantifierNOrMoreChange`), [`QuantifierNMModification`](#`QuantifierNMModification`), [`QuantifierShortModification`](#`QuantifierShortModification`), [`QuantifierShortChange`](#`QuantifierShortChange`), [`QuantifierReluctantAddition`](#`QuantifierReluctantAddition`)
```scala
"Pattern".toMutantAfterChildrenOf(token: RegexTree)
```

<sup>(*) If the given token has no child, the location of the given token is considered to be the location of the mutant</sup>

### Example
Here is an example of a simple case of adaptation. This will produce the same `Mutant`s as before this PR.

```scala
// Before
object PredefCharClassNegation extends TokenMutator {
  // ...
  override def mutate(token: RegexTree): Seq[String] = (token match {
    case pdcc: PredefinedCharClass =>
      Seq(pdcc.copy(charClass = pdcc.charClass.toggleCase))
    case _ => Nil
  }) map (_.build)
}

// After
object PredefCharClassNegation extends TokenMutator {
  // ...
  override def mutate(token: RegexTree): Seq[Mutant] = (token match {
    case pdcc: PredefinedCharClass =>
      Seq(pdcc.copy(charClass = pdcc.charClass.toggleCase))
    case _ => Nil
  }) map (_.build.toMutantOf(token)) // Convert into `Mutant`
}
```
*See the file changes of this PR for more examples.*

### CODE REVIEW

**Review by hugo-vrijswijk — COMMENTED** [review]
Wow, what a wonderfully documented PR! Code looks good to me. Clean and descriptive!

If I understand correctly, the locations of mutants should now be much more accurate (smaller)? We'll have to start using this in Stryker4s soon 😃. 

If the positions of mutants have changed, shouldn't some tests also have had to change? Or maybe there's a couple missing for mutant positions

**Review by wijtserekker — APPROVED** [review]
Awesome solution! And A+ for the detailed PR :smile:

**Comment by Nhaajt** [comment]
> Wow, what a wonderfully documented PR! Code looks good to me. Clean and descriptive!

Thanks!

> If I understand correctly, the locations of mutants should now be much more accurate (smaller)? We'll have to start using this in Stryker4s soon 😃.

The mutation location should be more accurate now and better tell the actual character range that was mutated in the input regex string. This is especially useful in regex with long containers (group, character class, concat, or, …) and regex syntax on long containers.

> If the positions of mutants have changed, shouldn't some tests also have had to change? Or maybe there's a couple missing for mutant positions

Indeed, we yet to have tests that check for mutation locations 😅, but we definitely will when we rework and reorganize the tests.

**Review by JSmits-utwente — APPROVED** [review]
Awesome PR! Very elegant solution. It will be cool to see the improved locations in Stryker's report!

**Pull request merged**
